Build process.c with _GNU_SOURCE
apple/swift-tools-support-core pull request #363
Opened 2022-11-04 07:16 UTC by fweimer-rh

Otherwise the build will fail on glibc 2.29 and later because posix_spawn_file_actions_addchdir_np is not declared.

A glibc change has been submitted as well, but it will not become available until glibc 2.37:

[PATCH] posix: Make posix_spawn extensions available by default https://sourceware.org/pipermail/libc-alpha/2022-November/143197.html

2022-11-04 11:30 UTC, MaxDesiatov commented
@swift-ci please test

2022-11-04 16:19 UTC, neonichu approved these changes

2022-11-04 19:36 UTC, compnerd requested changes
This runs the risk of causing warnings such as `macro redefined`.  You should add a check around this or better yet, sink this into the build system.

2022-11-04 19:47 UTC, compnerd commented
IIRC it does if it is from the command line vs builtin vs in the source.  At least with CMake we can control it on a per source file level, which keeps the risk profile the same.  However, a `#ifndef` wrapper seems fine too.

2022-11-04 20:02 UTC, compnerd commented
I think that we do have squashes on this repo, so either is fine - it can be squashed before merging.

2022-11-07 09:49 UTC, MaxDesiatov commented
@swift-ci please smoke test

2022-11-07 09:49 UTC, MaxDesiatov commented
@swift-ci please test

2022-11-07 15:37 UTC, compnerd approved these changes

2022-11-07 20:19 UTC, merged